version: '3'
 
services:
   unifi:
     image: plonxyz/unifi:latest
     volumes:
       - ./unifi_data:/UniFi/data
     restart: on-failure
     ports: 
      - "8443:8443"
      - "6789:6789"
      - "8080:8080" 
      - "8880:8880"
      - "8843:8843"
      - "3478:3478/udp"
     depends_on:
      - db
     links: 
      - "db:mongo"

 
   db:   
     image: mongo:latest
     volumes:
          - ./data/db:/data/db
     restart: on-failure
            
